language: python
rust:
  - nightly
python:
  - "3.5"
before_script:
  - "curl -sL https://static.rust-lang.org/rustup.sh -o ~/rust-installer/rustup.sh"
  - "sh ~/rust-installer/rustup.sh --prefix=~/rust --spec=nightly -y --disable-sudo 2> /dev/null"
  - "python setup.py install"
  - "cd example; python setup.py install; cd .."
script:
  - "python setup.py test"
