language: rust
rust:
  - nightly
python:
  - "3.5"
install:
  - "sudo apt-get install python3"
  - "python setup.py install"
  - "cd example; python setup.py install; cd .."
script:
  - "python setup.py test"
