language: rust
rust:
  - nightly
python:
  - "3.5"
install:
  - "source ~/virtualenv/python3.5/bin/activate"
  - "python setup.py install"
  - "cd example; python setup.py install; cd .."
script:
  - "python setup.py test"
